{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "katalyst-controller.serviceAccountName" . }}
rules:
  - apiGroups:
      - node.katalyst.kubewharf.io
    resources:
      - customnoderesources
      - customnoderesources/status
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - delete
  - apiGroups:
      - config.katalyst.kubewharf.io
      - autoscaling.katalyst.kubewharf.io
      - workload.katalyst.kubewharf.io
      - overcommit.katalyst.kubewharf.io
      - tide.katalyst.kubewharf.io
      - recommendation.katalyst.kubewharf.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - delete
      - update
  - apiGroups:
      - apps
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "katalyst-controller.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "katalyst-controller.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "katalyst-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "katalyst-controller.serviceAccountName" . }}
  labels:
    {{- include "katalyst-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
