# Overrides katalyst-controller values
katalyst-controller:
  enabled: true

  fullnameOverride: katalyst-controller

  replicaCount: 1

  image:
    registry: docker.io
    repository: kubewharf/katalyst-controller
    pullPolicy: IfNotPresent
    tag: ""

  customArgs:
    controllers: "resourcerecommender"
    dry-run: false
    leader-elect: true
    healthz-enabled: true
    resourcerecommend-prometheus-address: http://your-prom-address # visit more info at gokatalyst.io
    dynamic-resources: deployments.v1.apps
    v: 2
